name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt-get install -y g++ cmake

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run Tests
        run: |
          cd build
          ./mytelegram
